function [ out_str ] = Fieldname2Pretty( fieldname )
%FIELDNAME2PRETTY makes the field name pretty

    out_str = regexprep(...
        strrep(...
            strrep(...
                regexprep(fieldname,'[A-Z]',' $0'), '.', ' - ')...
            , '_', ' ')...
        , '(\<[a-z])', '${upper($1)}');

end

